name: Build & Release

on: push

jobs:
  build:
    name: Build
    runs-on: [macos-latest, macos-13]
    steps:
      - name: Setup GraalVM environment
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: "graalvm"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v3
        id: maven-cache # use this to check for `cache-hit` (`steps.yarn-and-maven-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.m2/
          key: ${{ runner.os }}-maven-${{ hashFiles('./deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          lein: latest
      - name: Install joker
        run: |
          brew install candid82/brew/joker
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: lein deps
      - name: Compile
        run: make
      - name: Test The Binary
        run: make test-binary
      - name: Create gokuw
        run: |
          touch gokuw
          echo '#!/bin/sh' >> gokuw
          echo 'watchexec -r -e edn -w `[[ -z $GOKU_EDN_CONFIG_FILE ]] && echo ~/.config/karabiner.edn || echo $GOKU_EDN_CONFIG_FILE` goku' >> gokuw
          chmod +x gokuw
      - name: Set artifact name
        id: set-name
        run: |
          if [[ "${{ runner.arch }}" == "ARM64" ]]; then
            echo "artifact_name=goku-aarch64-apple-darwin.zip" >> $GITHUB_OUTPUT
          else
            echo "artifact_name=goku-x86_64-apple-darwin.zip" >> $GITHUB_OUTPUT
          fi
      - name: Pack
        run: zip -r ${{ steps.set-name.outputs.artifact_name }} goku gokuw
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-name.outputs.artifact_name }}
          path: ${{ steps.set-name.outputs.artifact_name }}

  draft-release:
    name: Draft Release
    if: startsWith(github.ref, 'refs/heads/')
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: goku-x86_64-applle-darwin.zip
      - uses: actions/download-artifact@v5
        with:
          name: goku-aarch64-apple-darwin.zip
      - name: Delete Other Draft Releases
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get sha256 arm
        id: sha256-arm
        run: echo "::set-output name=checksum::$(shasum -a 256 goku-aarch64-apple-darwin.zip)"

      - name: Get sha256 intel
        id: sha256-intel
        run: echo "::set-output name=checksum::$(shasum -a 256 goku-x86_64-applle-darwin.zip)"

      - name: Draft release
        id: draft-release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          name: Release ${{ github.sha }}
          draft: true
          prerelease: false
          files: |
            goku-aarch64-apple-darwin.zip
            goku-x86_64-applle-darwin.zip
          body: |
            - goku-aarch64-apple-darwin.zip sha256 `${{ steps.sha256-arm.outputs.checksum }}`
            - goku-x86_64-applle-darwin.zip sha256 `${{ steps.sha256-intel.outputs.checksum }}`

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: goku-x86_64-applle-darwin.zip
      - uses: actions/download-artifact@v5
        with:
          name: goku-aarch64-apple-darwin.zip
      - name: Get sha256 arm
        id: sha256-arm
        run: echo "::set-output name=checksum::$(shasum -a 256 goku-aarch64-apple-darwin.zip)"

      - name: Get sha256 intel
        id: sha256-intel
        run: echo "::set-output name=checksum::$(shasum -a 256 goku-x86_64-applle-darwin.zip)"
      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Checkout the changelog at https://github.com/yqrashawn/GokuRakuJoudo/blob/master/CHANGELOG.org
            - goku-aarch64-apple-darwin.zip sha256 `${{ steps.sha256-arm.outputs.checksum }}`
            - goku-x86_64-applle-darwin.zip sha256 `${{ steps.sha256-intel.outputs.checksum }}`
          draft: false
          prerelease: false
          files: |
            goku-aarch64-apple-darwin.zip
            goku-x86_64-applle-darwin.zip
